### ISSUE TITLE
Even after removing role suitecrm, the user can still login

### ISSUE THREAD

**Issue by ganesh-at-wiw** [GluuFederation/suitecrm-oxd-module#2]
After specifying role suitecrm, the user can login. Upto this it's fine.
When we remove the role, the user can still login. The user should not be able to login if the particular role is removed.
For example, if the user needs to be prevented from logging into suitecrm and allow only roundcube or wordpress. But by chance we forget the removal or deactivation of his account at suitecrm. Then also the user can login into suitecrm.
The roundcube plugin works fine though.

**Comment by dollar007** [comment]
done
