### ISSUE TITLE
Can not connect to the oxd server

### ISSUE THREAD

**Issue by psynd** [GluuFederation/suitecrm-oxd-module#3]
I believe the plugin is not working correctly with the new version of Gluu or SuiteCRM, because the Oxd server is correctly configured and accessible, but I always get the following error message:

`Can not connect to the oxd server. Please check the oxd-config.json file to make sure you have entered the correct port and the oxd server is operational.`

**Comment by nynymike** [comment]
This plugin is not under development anymore.
